// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fF6aT-i4_6pzm6qwk4aC1jI_jTJ-klo',
    appId: '1:244826495706:web:68b1f0bca960639dbfa3e3',
    messagingSenderId: '244826495706',
    projectId: 'face-verification-test',
    authDomain: 'face-verification-test.firebaseapp.com',
    storageBucket: 'face-verification-test.appspot.com',
    measurementId: 'G-HE1623B60H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3d8MbjGqqoXChOmEuYZ0sPh-lWB4n_HY',
    appId: '1:244826495706:android:7eaf249f62669e3ebfa3e3',
    messagingSenderId: '244826495706',
    projectId: 'face-verification-test',
    storageBucket: 'face-verification-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW60vUnYrfRAZQuFVSN9Wa7Sv8Y6MhJXE',
    appId: '1:244826495706:ios:0521ef1233525f76bfa3e3',
    messagingSenderId: '244826495706',
    projectId: 'face-verification-test',
    storageBucket: 'face-verification-test.appspot.com',
    iosBundleId: 'com.Ricoloo.minimunFaceDetectorFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW60vUnYrfRAZQuFVSN9Wa7Sv8Y6MhJXE',
    appId: '1:244826495706:ios:d140102cf629ecd1bfa3e3',
    messagingSenderId: '244826495706',
    projectId: 'face-verification-test',
    storageBucket: 'face-verification-test.appspot.com',
    iosBundleId: 'com.Ricoloo.minimunFaceDetectorFlutter.RunnerTests',
  );
}
